### PR TITLE
Migrate to null safety and Android integration 2.0

### PR DESCRIPTION
**Pull request by adrienbaron**
*For null safety*:

- Upgrade SDK to `>=2.12.0` 
- Change `@required` to `required`

*For Android integration 2.0*:

Followed that guide: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects. Pretty sure it doesn't matter in the case of this lib but that gets rid of the warning on `flutter pub get` on the project

I also upgraded the version in `pubspec.yaml` to `2.0.0` as null safety upgrade is a breaking change for consumers (they need null safety on their project to consume the lib).

### CODE REVIEW

**Review by anoop4real — COMMENTED** [review]
Hello,
Thanks for taking your time to update the code and raising. I havent myself looked and nullsafety yet because of other project works. I will do a round of test and will take it from there

**Comment by anoop4real** [comment]
Hi,
I have merged PR, the examples were not upgraded, did that and fixed plugin formats etc... now its published . Please check and let me know if things working

**Comment by adrienbaron** [comment]
Thank you for the swift merge and release! I've updated my `pubspec.yaml` to point to your release:
```yaml

```

**Comment by adrienbaron** [comment]
Thank you for the swift merge and release! I've updated my `pubspec.yaml` to point to your release and ran pub get:
```yaml
iso_countries: ^2.0.1
```

Restarted my app in iOS simulator and everything seem to work OK:
image

No more warning in Dart Analysis about the package not supporting null safety either 💪 

Thanks again!

**Comment by anoop4real** [comment]
Great! thanks again for your effort

**Pull request merged**
